---
- name: 'Copy docker files to ansible'
  copy:
    src: 'templates/docker-application'
    dest: /home
  become: yes

- name: 'Run Docker Compose'
  docker_compose:
    project_src: /home/docker-application
    state: present
  become: yes
    # log_path: /var/log/my_application.log  # optional
