---
- name: 'Copy docker files to ansible'
  copy:
    src: 'files/docker-application'
    dest: /home

- name: 'Run Docker Compose'
  docker_compose:
    project_src: /home/docker-application
    state: present
