---
- name: 'Copy docker files to ansible'
  copy:
    src: 'files/docker-application'
    dest: /home
  become: yes

- name: 'Run Docker Compose'
  docker_compose:
    project_src: /home/application
    state: present
  become: yes
