---
- name: 'Install required packages for docker'
  apt:
    name: [
      'apt-transport-https',
      'ca-certificates',
      'curl',
      'gnupg-agent',
      'software-properties-common'
    ]
    state: present
  become: yes
  tags:
    - docker-installation

- name: 'Add Docker GPG key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
  become: yes
  tags:
    - docker-installation

- name: 'Add Docker apt repository'
  apt_repository:
    # ansible_lsb.codename is a value accessible after [gathering facts]
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  notify:
    - update cache
  become: yes
  tags:
    - docker-installation

- name: 'Docker installation'
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
    state: present
  become: yes
  tags:
    - docker-installation

- name: 'Install Python module'
  apt:
    name:
      - python3-pip  # Install pip for Python 3
  become: yes

- name: 'Install Docker Python module'
  pip:
    name: ['docker', 'docker-compose']
    executable: pip3  # Use pip3 for Python 3
  become: yes
