---
- name: 'Configure Nginx using template'
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: 'Enable Nginx service'
  systemd:
    name: nginx
    enabled: yes
    state: started
